services:
  caiman_server_database:
    # postgres:18-alpine - Repo: https://hub.docker.com/_/postgres
    image: postgres:18-alpine@sha256:1b1689b20d16a014a3d195653381cf2caa75a41a92d93b255a9d6ea29fd353aa
    container_name: caiman_server_database
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      # ADM
      POSTGRES_USER: admin_usr
      POSTGRES_PASSWORD: admin_pass
      POSTGRES_DB: caiman_server
    volumes:
      - caiman_server_database_vlm:/var/lib/postgresql

volumes:
  caiman_server_database_vlm:
    name: caiman_server_database_local_volume
