services:
  caiman-server:
#    image: under7/caiman-server:latest
    image: under7/caiman-server:v0.0.1-jvm
    container_name: caiman-server
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      CAIMAN_SERVER_PORT: 8080
      CAIMAN_SERVER_ENDPOINTS_PREFIX: /api
      CAIMAN_SERVER_LOGGING_LEVEL: INFO
      CAIMAN_SERVER_LOGGING_FOLDER_PATH: /app/logs
      CAIMAN_SERVER_LOGGING_FORMAT: UNSTRUCTURED
      CAIMAN_SERVER_DATABASE_TYPE: POSTGRES
      CAIMAN_SERVER_DATABASE_JDBC_URL: jdbc:postgresql://caiman-db:5432/caiman_server
      CAIMAN_SERVER_DATABASE_USERNAME: caiman_usr
      CAIMAN_SERVER_DATABASE_PASSWORD: caiman_pass
      CAIMAN_SERVER_OPEN_API_API_DOCS_PATH: /api-docs
      CAIMAN_SERVER_OPEN_API_API_DOCS_ENABLE: "true"
      CAIMAN_SERVER_OPEN_API_SWAGGER_UI_REDIRECT_PATH: /
      CAIMAN_SERVER_OPEN_API_SWAGGER_UI_ENABLE: "true"
    mem_limit: 384m
    depends_on:
      caiman-db:
        condition: service_healthy
    volumes:
      - caiman_logs:/app/logs

  caiman-db:
    # postgres:18-alpine - Repo: https://hub.docker.com/_/postgres
    image: postgres:18-alpine@sha256:1b1689b20d16a014a3d195653381cf2caa75a41a92d93b255a9d6ea29fd353aa
    container_name: caiman-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: caiman_usr
      POSTGRES_PASSWORD: caiman_pass
      POSTGRES_DB: caiman_server
    volumes:
      - caiman_db_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U caiman_usr -d caiman_server"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  caiman_logs:
    name: caiman_logs
  caiman_db_data:
    name: caiman_db_data
