package com.caimanproject.web.dto.response;

import io.swagger.v3.oas.annotations.media.Schema;
import java.time.Instant;
import lombok.Builder;

@Schema(description = "Standard error response returned by all Caiman endpoints when an exception occurs.")
@Builder
public record ErrorResponseDto(
        @Schema(
                description = "Full error code identifying the module and error type. Format: {MODULE_PREFIX}_{code}.",
                example = "WEB_SUPPORT_002",
                nullable = false,
                requiredMode = Schema.RequiredMode.REQUIRED)
        String code,

        @Schema(
                description = "Timestamp when the error occurred (UTC).",
                example = "2026-06-11T14:30:00Z",
                nullable = false,
                requiredMode = Schema.RequiredMode.REQUIRED)
        Instant timestamp,

        @Schema(
                description = "Human-readable error message.",
                example = "Some invalid values were sent",
                nullable = false,
                requiredMode = Schema.RequiredMode.REQUIRED)
        String message,

        @Schema(
                description =
                        "Additional detail about the error, such as which fields failed validation. Present only when applicable.",
                example = "[ propertyPath: email - errorMotive: must not be blank - valueProvided: null ]",
                nullable = true,
                requiredMode = Schema.RequiredMode.NOT_REQUIRED)
        String detail,

        @Schema(
                description = "Unique identifier for this request, generated by the server on every inbound request.",
                example = "d290f1ee-6c54-4b01-90e6-d701748f0851",
                nullable = false,
                requiredMode = Schema.RequiredMode.REQUIRED)
        String requestId,

        @Schema(
                description =
                        "Correlation ID propagated from the X-Correlation-ID request header. Null if not provided by the caller.",
                example = "f47ac10b-58cc-4372-a567-0e02b2c3d479",
                nullable = true,
                requiredMode = Schema.RequiredMode.NOT_REQUIRED)
        String correlationId,

        @Schema(
                description =
                        "Channel identifier propagated from the X-Channel request header. Free-string defined by the caller. Null if not provided.",
                example = "WEB",
                nullable = true,
                requiredMode = Schema.RequiredMode.NOT_REQUIRED)
        String channel,

        @Schema(
                description = "HTTP status code of the response.",
                example = "400",
                nullable = false,
                requiredMode = Schema.RequiredMode.REQUIRED)
        int httpStatusCode) {}
