name: Install just
description: Wraps taiki-e/install-action with a pinned SHA to install just 1.53.0.

runs:
  using: composite
  steps:
    # v2.82.0 - Repo: https://github.com/taiki-e/install-action
    - uses: taiki-e/install-action@b8cecb83565409bcc297b2df6e77f030b2a468d5
      with:
        tool: just@1.53.0
