name: Docker Login
description: Wraps docker/login-action with a pinned SHA.

inputs:
  username:
    required: true
    description: Docker Hub username
  password:
    required: true
    description: Docker Hub token or password

runs:
  using: composite
  steps:
    # v4.2.0 - Repo: https://github.com/docker/login-action
    - uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee
      with:
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}
